Layout/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Documentation:
 Enabled: false

Style/GlobalVars:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
